-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
  decoration = {
    active_opacity = 1,
    inactive_opacity = 1,
  },
})

hl.config({
  general = {
    layout = "scrolling",
  },
})

hl.config({
  input = {
    sensitivity = 0.24,
  },
})


-- Full opacity: Omarchy tags every window and fades it to 0.985, which
-- multiplies with the opacity settings, so 100% renders at 98.5%.
o.window(".*", { opacity = "1.0 1.0" })
