[menu]
background                = "#252422"
background-alpha          = 1.0
text                      = "#e8e5df"
border                    = "#5a5752"
border-alpha              = 1.0
scrim                     = "#000000"
scrim-alpha               = 0.55
selected-background       = "#4a463f"
selected-background-alpha = 1.0
selected-text             = "#8fd18a"
selected-border           = "#4a463f"
selected-border-alpha     = 0.0
